
USE [master]


ALTER DATABASE CAFM_Produktiv SET RECOVERY SIMPLE WITH NO_WAIT

-- SELECT * FROM sys.database_files 
DBCC SHRINKFILE(CAFM_Produktiv_Tlog, 1)
DBCC SHRINKDATABASE (CAFM_Produktiv, 10);
ALTER DATABASE CAFM_Produktiv SET RECOVERY FULL WITH NO_WAIT
GO


USE CAFM_Produktiv 
